[package]
name = "revist"
version = "0.1.0"
authors = ["Aaron Kofsky <aaronko@umich.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vst = "0.2.1"
wmidi = "4.0.1"
rand = "0.7.3"
log = "0.4.11"
simple-logging = "2.0.2"

[lib]
crate-type = ["cdylib"]
